services:
    - docker

git:
    depth: 1

before_install:
    #- docker pull dockcross/manylinux-x64
    - docker build -t manylinux-x64-custom -f docker/Dockerfile.manylinux-x64-custom .

install:
    #- docker run --rm dockcross/manylinux-x64 > ./dockcross_manylinux-x64
    - docker run --rm manylinux-x64-custom > ./dockcross_manylinux-x64
    - chmod +x ./dockcross_manylinux-x64
    - git clone --depth 1 -b v1.2.11 https://github.com/madler/zlib
    - git clone --depth 1 -b 7.0.1 https://github.com/leethomason/tinyxml2
    - git clone --depth 1 https://github.com/curl/curl
    - git clone --depth 1 https://github.com/openssl/openssl
    - git clone --depth 1 -b cares-1_15_0 https://github.com/c-ares/c-ares
    - git clone --depth 1 -b v3.6.1 https://github.com/google/protobuf
    - git clone -b hardcoded-musl-libc-compat https://github.com/dronecore/grpc
    - git clone -b external-deps-without-termios2 https://github.com/dronecode/dronecodesdk --recursive

script:
    - set -e
    - mkdir -p ${TRAVIS_BUILD_DIR}/install
    - ./dockcross_manylinux-x64 cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_POSITION_INDEPENDENT_CODE=ON -Bzlib/build -Szlib
    - ./dockcross_manylinux-x64 make -Czlib/build install
    - rm -rf install/lib/libz.so*
    - ./dockcross_manylinux-x64 cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_SHARED_LIBS=OFF -Btinyxml2/build -Stinyxml2
    - ./dockcross_manylinux-x64 make -Ctinyxml2/build install
    - ./dockcross_manylinux-x64 cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_USE_OPENSSL=OFF -DCURL_CA_PATH_SET=OFF -DHAVE_POSIX_STRERROR_R=1 -DBUILD_SHARED_LIBS=NO -Bcurl/build -Scurl
    - ./dockcross_manylinux-x64 make -Ccurl/build install
    - ./dockcross_manylinux-x64 bash -c "cd openssl && ./config --prefix=/install no-shared"
    - ./dockcross_manylinux-x64 --args "-v ${TRAVIS_BUILD_DIR}/install:/install" bash -c "make -Copenssl install > /dev/null"
    - ./dockcross_manylinux-x64 cmake -DCMAKE_INSTALL_PREFIX=install -DCARES_SHARED=OFF -DCARES_STATIC=ON -DCARES_STATIC_PIC=ON -Bc-ares/build -Sc-ares
    - ./dockcross_manylinux-x64 make -Cc-ares/build install
    - ./dockcross_manylinux-x64 cmake -DCMAKE_INSTALL_PREFIX=install -Dprotobuf_BUILD_TESTS=OFF -Bprotobuf/build -Sprotobuf/cmake
    - ./dockcross_manylinux-x64 make -Cprotobuf/build install
    - ./dockcross_manylinux-x64 cmake -DCMAKE_PREFIX_PATH=/work/install -DCMAKE_INSTALL_PREFIX=install -DZLIB_ROOT=/work/install -DgRPC_INSTALL_default=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_PROTOBUF_PACKAGE_TYPE=CONFIG -DgRPC_SSL_PROVIDER=package -Bgrpc/build -Sgrpc
    - ./dockcross_manylinux-x64 make -Cgrpc/build install
    - ./dockcross_manylinux-x64 cmake -DCMAKE_PREFIX_PATH=/work/install -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_BACKEND=YES -Bdronecodesdk/build/default -Sdronecodesdk
    - ./dockcross_manylinux-x64 make -Cdronecodesdk/build/default install
