services:
    - docker

git:
    depth: 1

before_install:
#    - docker pull dockcross/manylinux-x64
    - docker build -t manylinux-x64-custom -f docker/Dockerfile.manylinux-x64-custom .

install:
    - docker run --rm manylinux-x64-custom > ./dockcross_manylinux-x64
    - chmod +x ./dockcross_manylinux-x64
#    - git clone --depth 1 https://github.com/curl/curl
    - git clone --depth 1 https://github.com/openssl/openssl
    - git clone --depth 1 -b cares-1_15_0 https://github.com/c-ares/c-ares
    - git clone --depth 1 -b v3.6.1 https://github.com/google/protobuf
    - git clone -b hardcoded-musl-libc-compat https://github.com/dronecore/grpc

script:
    - set -e
    - mkdir -p ${TRAVIS_BUILD_DIR}/install
#    - cd ${TRAVIS_BUILD_DIR}/curl
#    - ../dockcross_manylinux-x64 cmake -DCMAKE_USE_OPENSSL=OFF -DCURL_CA_PATH_SET=OFF -DHAVE_POSIX_STRERROR_R=1 -Bbuild -S.
#    - ../dockcross_manylinux-x64 make -Cbuild
    - ./dockcross_manylinux-x64 bash -c "cd openssl && ./config --prefix=/install"
    - ./dockcross_manylinux-x64 --args "-v ${TRAVIS_BUILD_DIR}/install:/install" bash -c "make -Copenssl > /dev/null && make -Copenssl install > /dev/null"
    - ./dockcross_manylinux-x64 cmake -DCMAKE_INSTALL_PREFIX=install -Bc-ares/build -Sc-ares
    - ./dockcross_manylinux-x64 make -Cc-ares/build install
    - ./dockcross_manylinux-x64 cmake -DCMAKE_INSTALL_PREFIX=install -Dprotobuf_BUILD_TESTS=OFF -Bprotobuf/build -Sprotobuf/cmake
    - ./dockcross_manylinux-x64 make -Cprotobuf/build install
    - ./dockcross_manylinux-x64 cmake -DCMAKE_FIND_ROOT_PATH="/work/install;/work/grpc;/work/grpc/build;/work/grpc/build/bin" -DCMAKE_INSTALL_PREFIX=install -DgRPC_INSTALL_default=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_PROTOBUF_PACKAGE_TYPE=CONFIG -DgRPC_SSL_PROVIDER=package -Bgrpc/build -Sgrpc
    - ./dockcross_manylinux-x64 make -Cgrpc/build install
